version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - dgstn_net

  web:
    build: .
    # Используем gunicorn для работы на сервере
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
      - media_data:/code/media
      - static_data:/code/static_result  # Добавляем волюм для статики
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - dgstn_net
      - npm_network

networks:
  dgstn_net:
    driver: bridge
  npm_network:
    external: true

volumes:
  postgres_data:
  media_data:
  static_data: # Объявляем волюм для статики