# Generated by Django 5.2.13 on 2026-04-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Открой сердце гор', max_length=200, verbose_name='Заголовок на главном экране')),
                ('hero_subtitle', models.TextField(default='Индивидуальные и групповые путешествия по самым живописным уголкам Дагестана.', verbose_name='Подзаголовок')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='Фоновое фото (Hero)')),
            ],
            options={
                'verbose_name': 'Настройки Главной страницы',
                'verbose_name_plural': 'Настройки Главной страницы',
            },
        ),
    ]
