# Generated by Django 6.0.4 on 2026-04-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_alter_feedback_options_feedback_tour'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelcomeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Заголовок (напр. 14 коренных)')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='Подзаголовок (напр. народов)')),
                ('file', models.FileField(upload_to='welcome/', verbose_name='Файл (Медиа)')),
                ('media_type', models.CharField(choices=[('video', 'Видео'), ('photo', 'Фото')], default='photo', max_length=10, verbose_name='Тип контента')),
                ('is_large', models.BooleanField(default=False, verbose_name='Большая карточка (на 2 строки)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Блок приветствия',
                'verbose_name_plural': 'Блоки приветствия',
                'ordering': ['order'],
            },
        ),
    ]
