# Generated by Django 6.0.4 on 2026-04-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_category_tour_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='is_group_tour',
            field=models.BooleanField(default=False, verbose_name='Групповой тур?'),
        ),
    ]
