# Generated by Django 6.0.4 on 2026-04-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0006_tour_is_group_tour"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Имя")),
                ("city", models.CharField(blank=True, max_length=100, verbose_name="Город")),
                ("rating", models.PositiveSmallIntegerField(default=5, verbose_name="Оценка")),
                ("text", models.TextField(verbose_name="Текст отзыва")),
                ("likes_count", models.PositiveIntegerField(default=0, verbose_name="Лайки")),
                ("is_approved", models.BooleanField(default=False, verbose_name="Одобрен")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создан")),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
                "ordering": ["-created_at"],
            },
        ),
    ]
