# Generated by Django 6.0.4 on 2026-04-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0007_review"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Имя")),
                ("text", models.TextField(verbose_name="Комментарий")),
                ("is_approved", models.BooleanField(default=False, verbose_name="Одобрен")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создан")),
                ("review", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="comments", to="tours.review", verbose_name="Отзыв")),
            ],
            options={
                "verbose_name": "Комментарий к отзыву",
                "verbose_name_plural": "Комментарии к отзывам",
                "ordering": ["-created_at"],
            },
        ),
    ]
