# Generated by Codex on 2026-05-03

from django.db import migrations, models


REQUIRED_CATEGORIES = [
    ("Джип-туры", "jeep-tours"),
    ("Оздоровительные", "wellness"),
    ("Однодневные", "one-day"),
    ("Многодневные", "multi-day"),
    ("Семейные", "family"),
    ("Активный отдых", "active"),
    ("Комбинированные", "combined"),
]


def seed_sales_content(apps, schema_editor):
    Category = apps.get_model("tours", "Category")
    Tour = apps.get_model("tours", "Tour")

    categories = {}
    for name, slug in REQUIRED_CATEGORIES:
        category, _ = Category.objects.get_or_create(slug=slug, defaults={"name": name})
        categories[slug] = category

    presets = {
        "wellness": {
            "category": "wellness",
            "short_description": (
                "Оздоровительный отдых с термальными и минеральными источниками, "
                "мягким темпом поездки и маршрутом под самочувствие гостей."
            ),
            "duration": "3-15 дней",
            "trip_format": "Персональный, парный, семейный или компания",
            "included_items": "\n".join(
                [
                    "Трансфер из аэропорта и обратно",
                    "Размещение в гостевом доме по договоренности",
                    "Посещение источников с учетом самочувствия",
                    "Сопровождение гида",
                    "Экскурсии и национальная кухня по маршруту",
                ]
            ),
        },
        "jeep": {
            "category": "jeep-tours",
            "short_description": (
                "Горные дороги, видовые точки, высокогорные маршруты и безопасное "
                "сопровождение гида на всем пути."
            ),
            "duration": "3-15 дней",
            "trip_format": "Персональный, семейный или компания от 4 человек",
            "included_items": "\n".join(
                [
                    "Трансфер из аэропорта и обратно",
                    "Джип-маршрут по горам",
                    "Сопровождение гида",
                    "Гостевой дом по договоренности",
                    "Кулинарные мастер-классы по возможности",
                ]
            ),
        },
        "combined": {
            "category": "combined",
            "short_description": (
                "Комбинация гор, моря, кухни, экскурсий и отдыха в одном маршруте "
                "с гибкой программой по дням."
            ),
            "duration": "3-15 дней",
            "trip_format": "Персональный, парный, семейный или компания",
            "included_items": "\n".join(
                [
                    "Трансфер по маршруту",
                    "Горные и природные локации",
                    "Сопровождение гида",
                    "Проживание по договоренности",
                    "Экскурсии и национальная кухня",
                ]
            ),
        },
    }

    for tour in Tour.objects.all():
        title = (tour.title or "").lower()
        preset = None
        if "оздоров" in title:
            preset = presets["wellness"]
        elif "джип" in title:
            preset = presets["jeep"]
        elif "комбинир" in title:
            preset = presets["combined"]

        if not preset:
            continue

        changed_fields = []
        if not tour.category_id:
            tour.category = categories[preset["category"]]
            changed_fields.append("category")
        for field in ("short_description", "duration", "trip_format", "included_items"):
            if not getattr(tour, field):
                setattr(tour, field, preset[field])
                changed_fields.append(field)
        if changed_fields:
            tour.save(update_fields=changed_fields)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0009_alter_review_options_feedback_user_review_is_pinned_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="tour_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("jeep", "Джип-тур"),
                    ("wellness", "Оздоровительный"),
                    ("one_day", "Однодневный"),
                    ("multi_day", "Многодневный"),
                    ("family", "Семейный"),
                    ("individual", "Индивидуальный"),
                    ("unknown", "Пока не знаю, нужна консультация"),
                ],
                default="",
                max_length=30,
                verbose_name="Тип тура",
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="duration",
            field=models.CharField(blank=True, default="", max_length=80, verbose_name="Длительность"),
        ),
        migrations.AddField(
            model_name="tour",
            name="included_items",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Каждый пункт с новой строки. На карточке показываются первые 5 пунктов.",
                verbose_name="Что входит",
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="short_description",
            field=models.CharField(
                blank=True,
                default="",
                help_text="1-2 коротких предложения. Длинное описание оставьте в поле ниже.",
                max_length=260,
                verbose_name="Короткое описание для карточки",
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="trip_format",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Например: персональный, парный, семейный, компания.",
                max_length=120,
                verbose_name="Формат поездки",
            ),
        ),
        migrations.RunPython(seed_sales_content, noop),
    ]
