# Generated by Codex on 2026-05-20

from django.db import migrations, models


REQUIRED_CATEGORIES = [
    (
        "Джип-туры",
        "jeep-tours",
        "Горные дороги, каньоны и аулы на внедорожнике с гибким темпом.",
        10,
    ),
    (
        "Оздоровительные",
        "wellness",
        "Спокойные маршруты с источниками, морем и бережным ритмом без медицинских обещаний.",
        20,
    ),
    (
        "Однодневные",
        "one-day",
        "Насыщенные поездки из Махачкалы без ночевки.",
        30,
    ),
    (
        "Многодневные",
        "multi-day",
        "Маршруты на несколько дней с проживанием и понятной логистикой.",
        40,
    ),
    (
        "Активный отдых",
        "active",
        "Катера, тропы, смотровые и маршруты для гостей, которым нужен драйв.",
        50,
    ),
    (
        "Комбинированные",
        "combined",
        "Горы, море, история, кухня и отдых в одной программе.",
        60,
    ),
]


RUSSIAN_TRANSLIT = {
    "а": "a",
    "б": "b",
    "в": "v",
    "г": "g",
    "д": "d",
    "е": "e",
    "ё": "e",
    "ж": "zh",
    "з": "z",
    "и": "i",
    "й": "y",
    "к": "k",
    "л": "l",
    "м": "m",
    "н": "n",
    "о": "o",
    "п": "p",
    "р": "r",
    "с": "s",
    "т": "t",
    "у": "u",
    "ф": "f",
    "х": "h",
    "ц": "ts",
    "ч": "ch",
    "ш": "sh",
    "щ": "sch",
    "ъ": "",
    "ы": "y",
    "ь": "",
    "э": "e",
    "ю": "yu",
    "я": "ya",
}


def ascii_slug(value):
    raw = "".join(RUSSIAN_TRANSLIT.get(char.lower(), char.lower()) for char in value)
    slug = []
    previous_dash = False
    for char in raw:
        if char.isalnum():
            slug.append(char)
            previous_dash = False
        elif not previous_dash:
            slug.append("-")
            previous_dash = True
    return "".join(slug).strip("-") or "tour"


TOUR_PRESETS = [
    {
        "title": "Сулакский каньон, Сарыкум и Нохъо за один день",
        "slug": "sulak-sarykum-noho-one-day",
        "category": "one-day",
        "categories": ["one-day", "jeep-tours", "active"],
        "short_description": "Главные природные точки рядом с Махачкалой: бархан, каньон, пещеры Нохъо, Чиркейская ГЭС и прогулка у воды.",
        "description": (
            "Маршрут для первого знакомства с Дагестаном: за один день вы увидите песчаный бархан, "
            "бирюзовый Сулакский каньон, пещерный комплекс Нохъо, видовые площадки и Чиркейскую ГЭС. "
            "Темп подстраивается под гостей: можно сделать больше остановок для фото, добавить катер или "
            "оставить больше времени на обед и спокойную прогулку."
        ),
        "duration": "1 день",
        "trip_format": "Индивидуально или мини-группа",
        "included_items": "Трансфер по маршруту\nСопровождение гида\nПомощь с билетами на локациях\nОстановки на смотровых\nКонсультация по одежде и погоде",
        "not_included_items": "Питание\nКатер и входные билеты, если выбираете дополнительные активности\nЛичные расходы",
        "route_points": "Бархан Сарыкум\nСулакский каньон\nПещеры Нохъо\nЧиркейская ГЭС\nГлаврыба или обед по маршруту",
        "itinerary": "Утро: выезд из Махачкалы и Сарыкум.\nДень: смотровые Сулакского каньона, Нохъо и Чиркейская ГЭС.\nВечер: обед или ужин по маршруту, возвращение в город.",
        "start_location": "Махачкала, Каспийск или аэропорт",
        "group_size": "1-6 гостей",
        "difficulty": "Легкий маршрут, часть локаций со ступенями",
        "season": "Круглый год по погоде",
        "what_to_take": "Удобную обувь\nВетровку\nВоду\nПовербанк",
        "important_notes": "Катер зависит от погоды и уровня воды. Финальный порядок точек лучше согласовать накануне.",
        "price": 12000,
        "is_group_tour": False,
        "is_featured": True,
        "static_image": "site/sulak-canyon.jpg",
    },
    {
        "title": "Дербент, Нарын-Кала и экраноплан Лунь",
        "slug": "derbent-naryn-kala-lun",
        "category": "one-day",
        "categories": ["one-day", "combined"],
        "short_description": "Исторический день на юге: крепость, старый город, Каспий и экраноплан на берегу.",
        "description": (
            "Однодневная поездка для тех, кто хочет увидеть древний Дербент и почувствовать южный ритм "
            "Дагестана. В программе крепость Нарын-Кала, старые кварталы, прогулка у моря и экраноплан Лунь. "
            "Маршрут можно сделать спокойным, семейным или более насыщенным с музеями и дегустациями."
        ),
        "duration": "1 день",
        "trip_format": "Индивидуально, семья или компания",
        "included_items": "Трансфер из Махачкалы или Каспийска\nСопровождение гида\nПрогулка по старому городу\nПомощь с билетами\nРекомендации по кафе и рынку",
        "not_included_items": "Входные билеты\nПитание\nЛичные покупки",
        "route_points": "Дербент\nКрепость Нарын-Кала\nСтарый город\nКаспийское море\nЭкраноплан Лунь",
        "itinerary": "Утро: дорога на юг и крепость.\nДень: старый город, обед и прогулка.\nВечер: экраноплан, Каспий и возвращение.",
        "start_location": "Махачкала, Каспийск или Дербент",
        "group_size": "1-6 гостей",
        "difficulty": "Легкий маршрут, есть пешая часть",
        "season": "Круглый год",
        "what_to_take": "Головной убор летом\nУдобную обувь\nНаличные на билеты и кафе",
        "important_notes": "Летом лучше выезжать раньше, чтобы не проходить крепость в сильную жару.",
        "price": 14000,
        "is_group_tour": False,
        "is_featured": True,
        "static_image": "Джип-тур - Все включено.jpg",
    },
    {
        "title": "Гуниб, Гамсутль и Салтинский водопад",
        "slug": "gunib-gamsutl-salti",
        "category": "active",
        "categories": ["active", "one-day", "jeep-tours"],
        "short_description": "Горный маршрут с пешим подъемом к аулу-призраку, видами Гуниба и каньоном Салтинского водопада.",
        "description": (
            "Маршрут для тех, кто хочет больше гор и движения. Вы увидите Гуниб, подниметесь к Гамсутлю, "
            "побываете у Салтинского водопада и сделаете остановки на видовых дорогах. День получается "
            "насыщенным, поэтому темп и количество точек лучше согласовать заранее."
        ),
        "duration": "1 день",
        "trip_format": "Индивидуально или мини-группа",
        "included_items": "Джип или комфортный транспорт по погоде\nСопровождение гида\nМаршрутные остановки\nПомощь с локальным транспортом к Гамсутлю\nПлан по погоде",
        "not_included_items": "Питание\nЛокальный транспорт или входные сборы, если потребуются\nЛичные расходы",
        "route_points": "Гуниб\nГамсутль\nСалтинский водопад\nВидовые дороги\nГорные аулы по маршруту",
        "itinerary": "Ранний выезд: дорога в горы.\nДень: Гамсутль, Гуниб и обед.\nВечер: Салтинский водопад и возвращение.",
        "start_location": "Махачкала или Гуниб по договоренности",
        "group_size": "1-5 гостей",
        "difficulty": "Средняя: есть подъем и каменистые участки",
        "season": "Лучше весна, лето и осень",
        "what_to_take": "Треккинговую или удобную обувь\nВоду\nКуртку\nСолнцезащиту",
        "important_notes": "После дождей маршрут к водопаду и подъем к Гамсутлю могут меняться.",
        "price": 17000,
        "is_group_tour": False,
        "is_featured": False,
        "static_image": "site/goor-cliff.jpg",
    },
    {
        "title": "Гоор и Кахиб на внедорожнике",
        "slug": "goor-kahib-jeep",
        "category": "jeep-tours",
        "categories": ["jeep-tours", "active", "combined"],
        "short_description": "Сторожевые башни, старые аулы, скальные выступы и горные дороги для сильных кадров.",
        "description": (
            "Поездка к древним аулам и видовым точкам, где Дагестан выглядит особенно кинематографично: "
            "каменные башни, скальные выступы, узкие дороги и открытые панорамы. Это хорошая программа "
            "для тех, кто уже видел Сулак или хочет более редкий маршрут."
        ),
        "duration": "1-2 дня",
        "trip_format": "Джип-формат, индивидуально или компания",
        "included_items": "Внедорожник по маршруту\nСопровождение гида\nОстановки на смотровых\nПомощь с гостевым домом при ночевке\nГибкий план по погоде",
        "not_included_items": "Питание\nПроживание при двухдневном формате\nЛичные расходы",
        "route_points": "Старый Гоор\nКахиб\nСмотровые площадки\nСкальные выступы\nГорные дороги",
        "itinerary": "Формат 1 день: ранний выезд, основные точки и возвращение.\nФормат 2 дня: больше времени на фото, аулы и спокойный вечер в горах.",
        "start_location": "Махачкала или горный район по договоренности",
        "group_size": "1-4 гостя в машине",
        "difficulty": "Средняя: дороги и тропы зависят от погоды",
        "season": "Весна, лето, осень; зимой по условиям дороги",
        "what_to_take": "Закрытую обувь\nТеплый слой\nВоду\nНаличные",
        "important_notes": "На некоторых точках нужна аккуратность: безопасность важнее кадра.",
        "price": 19000,
        "is_group_tour": False,
        "is_featured": True,
        "static_image": "site/goor-cliff.jpg",
    },
    {
        "title": "Дагестан за 3 дня: каньон, Дербент и горы",
        "slug": "dagestan-3-days-canyon-derbent-mountains",
        "category": "multi-day",
        "categories": ["multi-day", "combined", "jeep-tours"],
        "short_description": "Сбалансированный маршрут для первого приезда: Сулак, Дербент, Гуниб или горные аулы.",
        "description": (
            "Три дня, чтобы увидеть разные лица региона без гонки: природный день у Сулакского каньона, "
            "исторический день в Дербенте и горный день с аулами, водопадами или Гунибом. Программа "
            "собирается под даты, сезон и состав гостей."
        ),
        "duration": "3 дня / 2 ночи",
        "trip_format": "Индивидуально, пара, семья или компания",
        "included_items": "Трансфер по маршруту\nСопровождение гида\nПомощь с проживанием\nПлан по дням\nРекомендации по питанию",
        "not_included_items": "Проживание, если не согласовано отдельно\nПитание\nБилеты и активности\nАвиабилеты",
        "route_points": "Сулакский каньон\nСарыкум\nДербент\nНарын-Кала\nГуниб или горные аулы",
        "itinerary": "День 1: Сулакский каньон и Сарыкум.\nДень 2: Дербент, крепость и Каспий.\nДень 3: горы, аулы или водопады по погоде.",
        "start_location": "Аэропорт, Махачкала или Каспийск",
        "group_size": "1-6 гостей",
        "difficulty": "Комфортный темп, можно добавить активность",
        "season": "Круглый год",
        "what_to_take": "Документы\nУдобную обувь\nТеплый слой для гор\nНаличные",
        "important_notes": "Проживание можно включить в расчет после выбора класса гостевого дома.",
        "price": 39000,
        "is_group_tour": False,
        "is_featured": True,
        "static_image": "site/hero-boat-canyon.jpg",
    },
    {
        "title": "От гор к Каспию за 5 дней",
        "slug": "mountains-to-caspian-5-days",
        "category": "multi-day",
        "categories": ["multi-day", "combined", "wellness"],
        "short_description": "Маршрут с большим воздухом: горные дороги, Дербент, Каспий, кухня и спокойные вечера.",
        "description": (
            "Пятидневный сценарий для тех, кто не хочет выбирать между горами, морем и историей. "
            "В программу можно включить Сулак, Гуниб, Дербент, Каспийское побережье, локальную кухню "
            "и мягкий день отдыха без переездов."
        ),
        "duration": "5 дней / 4 ночи",
        "trip_format": "Индивидуальный маршрут",
        "included_items": "Трансфер по программе\nСопровождение гида\nПомощь с жильем\nГибкая программа по дням\nПодбор кафе и локальных точек",
        "not_included_items": "Проживание\nПитание\nВходные билеты и активности\nАвиабилеты",
        "route_points": "Сулакский каньон\nГорные аулы\nДербент\nКаспийское море\nКухня и ремесла",
        "itinerary": "День 1: прибытие и легкая прогулка.\nДень 2: Сулак и Сарыкум.\nДень 3: горы и аулы.\nДень 4: Дербент и Каспий.\nДень 5: свободный темп и выезд.",
        "start_location": "Аэропорт или Махачкала",
        "group_size": "1-6 гостей",
        "difficulty": "Комфортный темп",
        "season": "Круглый год, программа меняется по сезону",
        "what_to_take": "Одежду слоями\nУдобную обувь\nКупальные вещи летом\nНаличные",
        "important_notes": "Можно сделать маршрут более активным или спокойным после короткой консультации.",
        "price": 68000,
        "is_group_tour": False,
        "is_featured": False,
        "static_image": "site/boat-guests.jpg",
    },
    {
        "title": "Мягкая перезагрузка: море, горы и источники",
        "slug": "soft-reload-sea-mountains-springs",
        "category": "wellness",
        "categories": ["wellness", "combined", "multi-day"],
        "short_description": "Спокойный маршрут без перегруза: прогулки, виды, Каспий, источники и бережный темп.",
        "description": (
            "Оздоровительный формат без спорных обещаний: мы не лечим, а собираем спокойную поездку "
            "с красивыми местами, термальными или минеральными источниками по самочувствию, морем, "
            "короткими прогулками и понятной логистикой."
        ),
        "duration": "3-7 дней",
        "trip_format": "Пара, семья или индивидуально",
        "included_items": "Маршрут в мягком темпе\nТрансфер по программе\nСопровождение гида\nПомощь с проживанием\nУчет самочувствия и ограничений",
        "not_included_items": "Медицинские процедуры\nПроживание и питание, если не включены отдельно\nВходные билеты\nЛичные расходы",
        "route_points": "Каспийское море\nТермальные или минеральные источники\nДербент или Махачкала\nЛегкие горные смотровые\nНациональная кухня",
        "itinerary": "День 1: прибытие и спокойная прогулка.\nДни 2-3: источники, море и легкие выезды.\nДальше: горы, Дербент или свободный день по самочувствию.",
        "start_location": "Аэропорт, Махачкала или Каспийск",
        "group_size": "1-5 гостей",
        "difficulty": "Легкий и бережный темп",
        "season": "Круглый год",
        "what_to_take": "Купальные вещи\nУдобную обувь\nЛичные лекарства\nДокументы",
        "important_notes": "Перед источниками важно учитывать противопоказания и рекомендации врача.",
        "price": 42000,
        "is_group_tour": False,
        "is_featured": True,
        "static_image": "Оздоровительный тур - Все включено.jpg",
    },
    {
        "title": "Джип + оздоровительный отдых",
        "slug": "jeep-wellness-combo",
        "category": "combined",
        "categories": ["combined", "jeep-tours", "wellness"],
        "short_description": "Контрастный тур: видовые дороги и активный день чередуются с источниками, морем и спокойным вечером.",
        "description": (
            "Комбинированный формат для гостей, которые хотят и увидеть горы, и не устать от поездки. "
            "Маршрут чередует джип-дни с более мягкими днями: источники, Каспий, прогулки, кухня и отдых. "
            "Подходит для пары, семьи или небольшой компании."
        ),
        "duration": "4-6 дней",
        "trip_format": "Индивидуально или компания",
        "included_items": "Джип-маршрут по горам\nСпокойные дни отдыха\nТрансфер по программе\nСопровождение гида\nПомощь с проживанием",
        "not_included_items": "Проживание\nПитание\nБилеты и активности\nМедицинские процедуры",
        "route_points": "Сулакский каньон\nГорные дороги\nКаспийское море\nИсточники по самочувствию\nКухня и локальные точки",
        "itinerary": "День 1: прибытие и легкая программа.\nДень 2: джип-маршрут к каньону или горам.\nДень 3: источники или море.\nДни 4-6: Дербент, аулы или отдых по желанию.",
        "start_location": "Аэропорт или Махачкала",
        "group_size": "1-6 гостей",
        "difficulty": "Средний, можно смягчить",
        "season": "Круглый год",
        "what_to_take": "Одежду слоями\nКупальные вещи\nЗакрытую обувь\nНаличные",
        "important_notes": "Активные и спокойные дни можно менять местами по погоде и самочувствию.",
        "price": 56000,
        "is_group_tour": False,
        "is_featured": False,
        "static_image": "Комбинированный тур - Джип + Оздоровительный.jpg",
    },
]


def populate_catalog(apps, schema_editor):
    Category = apps.get_model("tours", "Category")
    Tour = apps.get_model("tours", "Tour")

    categories = {}
    for name, slug, description, order in REQUIRED_CATEGORIES:
        category, _ = Category.objects.update_or_create(
            slug=slug,
            defaults={"name": name, "description": description, "order": order},
        )
        categories[slug] = category

    legacy_family = Category.objects.filter(slug="family").first()
    if legacy_family:
        for tour in Tour.objects.filter(category=legacy_family):
            tour.category = categories["combined"]
            tour.save(update_fields=["category"])
        for tour in Tour.objects.filter(categories=legacy_family):
            tour.categories.add(categories["combined"])
            tour.categories.remove(legacy_family)
        legacy_family.delete()

    for tour in Tour.objects.all():
        if not tour.slug:
            base_slug = ascii_slug(tour.title)
            candidate = base_slug
            counter = 2
            while Tour.objects.filter(slug=candidate).exclude(pk=tour.pk).exists():
                candidate = f"{base_slug}-{counter}"
                counter += 1
            tour.slug = candidate
            tour.save(update_fields=["slug"])
        if tour.category_id:
            tour.categories.add(tour.category)

    for preset in TOUR_PRESETS:
        primary_category = categories[preset["category"]]
        defaults = {
            "title": preset["title"],
            "category": primary_category,
            "short_description": preset["short_description"],
            "description": preset["description"],
            "duration": preset["duration"],
            "trip_format": preset["trip_format"],
            "included_items": preset["included_items"],
            "not_included_items": preset["not_included_items"],
            "route_points": preset["route_points"],
            "itinerary": preset["itinerary"],
            "start_location": preset["start_location"],
            "group_size": preset["group_size"],
            "difficulty": preset["difficulty"],
            "season": preset["season"],
            "what_to_take": preset["what_to_take"],
            "important_notes": preset["important_notes"],
            "price": preset["price"],
            "is_group_tour": preset["is_group_tour"],
            "is_featured": preset["is_featured"],
            "is_published": True,
            "static_image": preset["static_image"],
        }
        existing = Tour.objects.filter(slug=preset["slug"]).first()
        if not existing:
            existing = Tour.objects.filter(title=preset["title"]).first()
        if existing:
            for field, value in defaults.items():
                setattr(existing, field, value)
            existing.slug = preset["slug"]
            existing.save()
            tour = existing
        else:
            tour = Tour.objects.create(slug=preset["slug"], **defaults)
        tour.categories.set([categories[slug] for slug in preset["categories"]])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("tours", "0010_tour_sales_fields_feedback_tour_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.CharField(blank=True, default="", max_length=220, verbose_name="Короткое описание"),
        ),
        migrations.AddField(
            model_name="category",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Порядок"),
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["order", "name"], "verbose_name": "Категория", "verbose_name_plural": "Категории"},
        ),
        migrations.AddField(
            model_name="tour",
            name="slug",
            field=models.SlugField(blank=True, default="", max_length=220, verbose_name="Слаг (для URL)"),
        ),
        migrations.AddField(
            model_name="tour",
            name="categories",
            field=models.ManyToManyField(blank=True, related_name="multi_category_tours", to="tours.category", verbose_name="Дополнительные категории"),
        ),
        migrations.AddField(
            model_name="tour",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, blank=True, null=True, verbose_name="Создан"),
        ),
        migrations.AddField(
            model_name="tour",
            name="difficulty",
            field=models.CharField(blank=True, default="", max_length=120, verbose_name="Сложность"),
        ),
        migrations.AddField(
            model_name="tour",
            name="group_size",
            field=models.CharField(blank=True, default="", max_length=120, verbose_name="Размер группы"),
        ),
        migrations.AddField(
            model_name="tour",
            name="important_notes",
            field=models.TextField(blank=True, default="", verbose_name="Важные примечания"),
        ),
        migrations.AddField(
            model_name="tour",
            name="is_featured",
            field=models.BooleanField(default=False, verbose_name="Показывать на главной"),
        ),
        migrations.AddField(
            model_name="tour",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Опубликован"),
        ),
        migrations.AddField(
            model_name="tour",
            name="itinerary",
            field=models.TextField(blank=True, default="", help_text="Короткий план по дням или по времени. Можно писать свободным текстом.", verbose_name="Программа"),
        ),
        migrations.AddField(
            model_name="tour",
            name="not_included_items",
            field=models.TextField(blank=True, default="", help_text="Каждый пункт с новой строки.", verbose_name="Что не входит"),
        ),
        migrations.AddField(
            model_name="tour",
            name="route_points",
            field=models.TextField(blank=True, default="", help_text="Каждая точка с новой строки: Сарыкум, Нохъо, Чиркейская ГЭС.", verbose_name="Ключевые точки маршрута"),
        ),
        migrations.AddField(
            model_name="tour",
            name="season",
            field=models.CharField(blank=True, default="", max_length=120, verbose_name="Сезон"),
        ),
        migrations.AddField(
            model_name="tour",
            name="start_location",
            field=models.CharField(blank=True, default="", max_length=140, verbose_name="Старт"),
        ),
        migrations.AddField(
            model_name="tour",
            name="static_image",
            field=models.CharField(blank=True, default="", help_text="Путь внутри static/images, например site/sulak-canyon.jpg. Используется, если не загружено главное фото.", max_length=220, verbose_name="Статичное фото"),
        ),
        migrations.AddField(
            model_name="tour",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, blank=True, null=True, verbose_name="Обновлен"),
        ),
        migrations.AddField(
            model_name="tour",
            name="what_to_take",
            field=models.TextField(blank=True, default="", help_text="Каждый пункт с новой строки.", verbose_name="Что взять с собой"),
        ),
        migrations.AlterField(
            model_name="tour",
            name="main_image",
            field=models.ImageField(blank=True, upload_to="tours/", verbose_name="Главное фото"),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="tour_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("jeep", "Джип-тур"),
                    ("wellness", "Оздоровительный"),
                    ("one_day", "Однодневный"),
                    ("multi_day", "Многодневный"),
                    ("active", "Активный отдых"),
                    ("combined", "Комбинированный"),
                    ("unknown", "Пока не знаю, нужна консультация"),
                ],
                default="",
                max_length=30,
                verbose_name="Тип тура",
            ),
        ),
        migrations.RunPython(populate_catalog, noop),
        migrations.AlterField(
            model_name="tour",
            name="slug",
            field=models.SlugField(blank=True, max_length=220, unique=True, verbose_name="Слаг (для URL)"),
        ),
    ]
